steps:
 - name: 'gcr.io/cloud-builders/docker'
   entrypoint: 'bash'
   args:
   - '-c'
   - |
     docker pull eu.gcr.io/$PROJECT_ID/am-worker:latest || exit 0      
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t', 'eu.gcr.io/$PROJECT_ID/am-worker:latest', '-t', 'eu.gcr.io/$PROJECT_ID/am-worker:$SHORT_SHA',
          '--cache-from','eu.gcr.io/$PROJECT_ID/am-worker:latest','-f','./Dockerfile', '.']
images: ['eu.gcr.io/$PROJECT_ID/am-worker']
tags: ['$SHORT_SHA']